# Generated by Django 3.2.6 on 2021-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('completed', models.CharField(choices=[('Accomplished', 'Accomplished'), ('Unaccomplished', 'Unaccomplished')], default='Unaccomplished', max_length=30)),
                ('notify', models.BooleanField(default=False)),
            ],
        ),
    ]
