# Generated by Django 3.2.6 on 2021-11-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0002_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
