# Generated by Django 3.0.2 on 2022-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_list', '0002_auto_20211223_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
